{
 "title": "Home - Energy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Electricity Consumed (High Tarif)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"consumption_high_tarif\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "consumption_high_tarif" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Electricity Produced (High Tarif)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"production_high_tarif\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "production_high_tarif" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Electricity used from net",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_power_consumption",
     "query": "SELECT -last(\"total_power_consumption\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time(1m) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Electricity injected into net",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_power_production",
     "query": "SELECT last(\"total_power_production\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time(1m) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Electricity Consumed (Low Tarif)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"consumption_low_tarif\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "consumption_low_tarif" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Electricity Produced (Low Tarif)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"production_low_tarif\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "production_low_tarif" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Gas Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"gas_meter_m3\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_meter_m3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Water Consumed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"water_meter_m3\") FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "water_meter_m3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Electricity Production",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"total_power_production\") FROM \"meter_data\"",
     "select": [
      [
       { "params": [ "total_power_production" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Electricity Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_data",
     "query": "SELECT last(\"total_power_consumption\") FROM \"meter_data\"",
     "select": [
      [
       { "params": [ "total_power_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Electricity used from net",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_power_consumption",
     "query": "SELECT -last(\"total_power_consumption\") FROM \"meter_data\" WHERE time > now()-24h GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Electricity injected into net",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_power_production",
     "query": "SELECT last(\"total_power_production\") FROM \"meter_data\" WHERE time > now()-24h GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Tarif",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "actual_tarif",
     "query": "SELECT last(\"actual_tarif\") FROM \"meter_data\" WHERE time > now()-24h GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Low tarif",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "actual_consumption",
     "query": "SELECT mean(\"total_power_consumption\")*24 FROM \"meter_data\" WHERE (\"actual_tarif\" =2)  GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tarif", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Normal tarif",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"total_power_consumption\")*24 FROM \"meter_data\" WHERE (\"actual_tarif\" =1)  GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "alias": "gas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gas_meter_m3",
     "query": "SELECT derivative(mean(\"gas_meter_m3\"), 1m) FROM \"meter_data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Decoded Datagrams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_stats",
     "query": "SELECT last(\"decoded\") FROM \"meter_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "decoded" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Published Datagrams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_stats",
     "select": [
      [
       { "params": [ "published" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meter Timeouts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_stats",
     "select": [
      [
       { "params": [ "timeouts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CDEM Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "meter_stats",
     "query": "SELECT last(\"uptime\") FROM \"meter_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CDEM Library Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "announce",
     "query": "SELECT last(\"lib-version\") FROM \"announce\"",
     "select": [
      [
       { "params": [ "lib-version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CDEM PCB Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "announce",
     "query": "SELECT last(\"pcb-version\") FROM \"announce\"",
     "select": [
      [
       { "params": [ "pcb-version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}